Part 2: SQL Programming
Overview

In this part of the assessment, you will act as a Data analyst to answer a research question on the US elections.

In [15]:
#Start by loading SQL extension into our environment
%load_ext sql
#Connect to in memory sqlite database
%sql sqlite://

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: @None'

In [16]:
#Import python liblaries required for this notebook
import csv
import pandas as pd

In [17]:
#Load data from GrandElectors_by_state csv file
with open('GrandElectors_by_state.csv','r') as j:
    Electors = pd.read_csv(j, index_col=0, encoding='utf-8')

In [18]:
#Drop existing tables that may be similar to Electors
%sql DROP TABLE if EXISTS Electors;
%sql PERSIST Electors;

 * sqlite://
Done.
 * sqlite://

'Persisted electors'

In [19]:
#Preview our Electors table, display the first 5 rows
%%sql
SELECT * from Electors LIMIT 5;

 * sqlite://
Done.

[('Alabama', 9),
 ('Alaska', 3),
 ('Arizona', 11),
 ('Arkansas', 6),
 ('California', 55)]

In [20]:
#Load data from Population_by_state csv file
with open('Population_by_state.csv','r') as k:
    Demograph = pd.read_csv(k, index_col=0, encoding='utf-8')

In [21]:
#Drop existing tables that may be similar to Demograph
%sql DROP TABLE if EXISTS Demograph;
%sql PERSIST Demograph;

 * sqlite://
Done.
 * sqlite://

'Persisted demograph'

In [22]:
#Preview our Demograph table, display the first 5 rows
%%sql
SELECT * from Demograph LIMIT 5;

 * sqlite://
Done.

[('CALIFORNIA', 39144818),
 ('TEXAS', 27469114),
 ('FLORIDA', 20271272),
 ('NEW YORK', 19795791),
 ('ILLINOIS', 12859995)]

Q1. To join the 2 tables to have a common state key

In [23]:
#we need to retain GrandElectors column from Grandelectors table
#We need to retain Population column from Population table
#we should have a column 'States', common to the two tables
#Start by converting states in Electors table to UPPERCASE
#Preview the data
%%sql
UPDATE Electors
SET State = UPPER(State);
SELECT * FROM Electors LIMIT 5;

 * sqlite://
51 rows affected.
Done.

[('ALABAMA', 9),
 ('ALASKA', 3),
 ('ARIZONA', 11),
 ('ARKANSAS', 6),
 ('CALIFORNIA', 55)]

In [24]:
#Join the two tables to have a common column for State

%%sql
CREATE TABLE IF NOT EXISTS ElectorsPopulation AS
SELECT State,GrandElectors, Population
FROM (SELECT * FROM Electors INNER JOIN Demograph 
     ON Electors.State = Demograph.State);
SELECT * FROM ElectorsPopulation LIMIT 10

 * sqlite://
Done.
Done.

[('ALABAMA', 9, 4858979),
 ('ALASKA', 3, 738432),
 ('ARIZONA', 11, 6828065),
 ('ARKANSAS', 6, 2978204),
 ('CALIFORNIA', 55, 39144818),
 ('COLORADO', 9, 5456574),
 ('CONNECTICUT', 7, 3590886),
 ('DC.', 3, 672228),
 ('DELAWARE', 3, 945934),
 ('FLORIDA', 29, 20271272)]

Q2. Change the name of the "District of Columbia" state to its short version "DC".

In [25]:
#Update the name of the record "District of Columbia" to "DC."
#Preview the table
%%sql
UPDATE ElectorsPopulation
SET State = "DC."
WHERE State = "DISTRICT OF COLUMBIA";
SELECT * FROM ElectorsPopulation LIMIT 10

 * sqlite://
0 rows affected.
Done.

[('ALABAMA', 9, 4858979),
 ('ALASKA', 3, 738432),
 ('ARIZONA', 11, 6828065),
 ('ARKANSAS', 6, 2978204),
 ('CALIFORNIA', 55, 39144818),
 ('COLORADO', 9, 5456574),
 ('CONNECTICUT', 7, 3590886),
 ('DC.', 3, 672228),
 ('DELAWARE', 3, 945934),
 ('FLORIDA', 29, 20271272)]

Q3. Compute the ratio between the number of grand electors and the population. Please create a new column with that ratio

In [33]:
#Ratio between grand electors and population, defined as: GrandElectors/Population
#Preview the table
%%sql
ALTER TABLE ElectorsPopulation
ADD IF NOT EXISTS GrandElectorsCapita float;
SELECT * FROM ElectorsPopulation LIMIT 12;

 * sqlite://
(sqlite3.OperationalError) near "EXISTS": syntax error
[SQL: ALTER TABLE ElectorsPopulation
ADD IF NOT EXISTS GrandElectorsCapita float;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Q4. Order the states by decreasing ratio of Grand Electors per capita. To make our priority list.

In [29]:
%%sql
UPDATE ElectorsPopulation
SET "GrandElectorsCapita" = Population/GrandElectors;
SELECT * FROM ElectorsPopulation
ORDER BY GrandElectorsCapita ASC LIMIT 10;

 * sqlite://
(sqlite3.OperationalError) no such column: GrandElectorsCapita
[SQL: UPDATE ElectorsPopulation
SET "GrandElectorsCapita" = Population/GrandElectors;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Q5. Compute the running total of Grand Electors in that sorted list.

In [14]:
#